blank_issues_enabled: false
contact_links:
  - name: Questions / Discussion
    url: https://github.com/Djordje3002/BarberShopAppointment/issues
    about: If you're not sure it's a bug, start with a question in an issue.
